# Generated by Django 6.0.2 on 2026-02-26 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_inquilino', models.CharField(max_length=150)),
                ('telefono_inquilino', models.CharField(max_length=20)),
                ('cedula_o_pasaporte', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_inquilino', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto_renta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_de_pago', models.IntegerField(help_text='Día del mes en que se genera la factura (1-31)')),
                ('dias_gracia', models.IntegerField(default=5, help_text='Días de gracia tras la fecha de pago antes de aplicar mora')),
                ('porcentaje_mora', models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: 5.00 para cobrar un 5% de mora', max_digits=5)),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('fotos_entrega', models.FileField(blank=True, null=True, upload_to='entregas_galeria/')),
                ('activo', models.BooleanField(default=True)),
                ('usuario_sistema', models.OneToOneField(blank=True, help_text='Solo si tendrá acceso al portal web', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(help_text='Fecha en la que terminan los días de gracia')),
                ('monto_base', models.DecimalField(decimal_places=2, help_text='Monto original de la renta facturada', max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ATRASADA', 'Atrasada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('concepto', models.CharField(max_length=255)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='gestion_propiedades.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='CargoMora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_aplicado', models.IntegerField(help_text='Mes en que se generó esta penalidad (1-12)')),
                ('anio_aplicado', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moras', to='gestion_propiedades.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Inversiones Familiares o Portafolio Principal', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_o_numero', models.CharField(help_text='Ej: Apt 2B, Casa #4, o Local Comercial 1', max_length=100)),
                ('grupo_o_residencial', models.CharField(blank=True, help_text='Ej: Residencial Los Pinos (Opcional, para agrupar)', max_length=100, null=True)),
                ('direccion_completa', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('detalles', models.TextField(blank=True, help_text='Ej: 2 habitaciones, 1 baño', null=True)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='gestion_propiedades.portafolio')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('REPARACION', 'Reparación'), ('PREVENTIVO', 'Mantenimiento Preventivo'), ('MEJORA', 'Mejora'), ('LIMPIEZA', 'Limpieza y Acondicionamiento')], max_length=20)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('factura_adjunta', models.FileField(blank=True, null=True, upload_to='comprobantes_mantenimiento/')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='gestion_propiedades.propiedad')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestion_propiedades.propiedad'),
        ),
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=20)),
                ('referencia_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_imagen', models.FileField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='gestion_propiedades.factura')),
            ],
        ),
    ]
