# Generated by Django 6.0.2 on 2026-02-26 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador Principal'), ('ASISTENTE', 'Asistente (Lectura y Cobros)')], default='ASISTENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='gestion_propiedades.portafolio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolios_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('portafolio', 'usuario')},
            },
        ),
    ]
