# Generated by Django 6.0.2 on 2026-03-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0002_accesoportafolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='foto_entrega_2',
            field=models.FileField(blank=True, null=True, upload_to='entregas_galeria/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='foto_entrega_3',
            field=models.FileField(blank=True, null=True, upload_to='entregas_galeria/'),
        ),
    ]
