# Generated by Django 6.0.2 on 2026-03-18 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0003_contrato_foto_entrega_2_contrato_foto_entrega_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_secreto', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Configurando preguntas)'), ('ENVIADA', 'Link enviado al prospecto'), ('RECIBIDA', 'Formulario Completado (Lista para evaluar)'), ('APROBADA', 'Aprobada (Lista para contrato)'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('nombre_completo', models.CharField(blank=True, max_length=150, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_personas', models.IntegerField(blank=True, null=True)),
                ('tiene_mascotas', models.BooleanField(default=False)),
                ('detalles_mascotas', models.CharField(blank=True, help_text='Ej: 1 perro raza pequeña', max_length=150, null=True)),
                ('profesion', models.CharField(blank=True, max_length=150, null=True)),
                ('ingresos_mensuales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preguntas_extra', models.TextField(blank=True, help_text='Escribe aquí las preguntas adicionales que quieres hacerle a este prospecto específico.', null=True)),
                ('respuestas_extra', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='gestion_propiedades.propiedad')),
            ],
        ),
    ]
