# Generated by Django 6.0.2 on 2026-03-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0004_solicitudalquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudalquiler',
            name='empresa_trabajo',
            field=models.CharField(blank=True, help_text='Empresa donde labora actualmente', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='telefono_empresa',
            field=models.CharField(blank=True, help_text='Teléfono de la empresa', max_length=20, null=True),
        ),
    ]
