# Generated by Django 5.2.10 on 2026-03-21 01:36

from django.db import migrations

def migrar_datos_inquilinos(apps, schema_editor):
    Contrato = apps.get_model('gestion_propiedades', 'Contrato')
    Inquilino = apps.get_model('gestion_propiedades', 'Inquilino')
    
    for contrato in Contrato.objects.all():
        inquilino, created = Inquilino.objects.get_or_create(
            nombre=contrato.nombre_inquilino,
            telefono=contrato.telefono_inquilino,
            defaults={
                'cedula_o_pasaporte': contrato.cedula_o_pasaporte,
                'correo': contrato.correo_inquilino,
                'usuario_sistema': contrato.usuario_sistema
            }
        )
        contrato.inquilino = inquilino
        contrato.save()

def revertir_datos_inquilinos(apps, schema_editor):
    Contrato = apps.get_model('gestion_propiedades', 'Contrato')
    for contrato in Contrato.objects.all():
        if contrato.inquilino:
            contrato.nombre_inquilino = contrato.inquilino.nombre
            contrato.telefono_inquilino = contrato.inquilino.telefono
            contrato.cedula_o_pasaporte = contrato.inquilino.cedula_o_pasaporte
            contrato.correo_inquilino = contrato.inquilino.correo
            contrato.usuario_sistema = contrato.inquilino.usuario_sistema
            contrato.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0006_alter_accesoportafolio_id_alter_cargomora_id_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_datos_inquilinos, revertir_datos_inquilinos),
    ]
