# Generated by Django 5.2.10 on 2026-03-21 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0007_auto_20260320_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cedula_o_pasaporte',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='correo_inquilino',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nombre_inquilino',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='telefono_inquilino',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='usuario_sistema',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='gestion_propiedades.inquilino'),
        ),
    ]
