# Generated by Django 5.2.10 on 2026-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0008_remove_contrato_cedula_o_pasaporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='monto_adelanto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto cobrado por alquiler adelantado', max_digits=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='monto_deposito',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto retenido como depósito (Fianza)', max_digits=10),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='config_meses_adelanto',
            field=models.IntegerField(default=0, help_text='Cantidad de meses exigidos por adelantado por defecto'),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='config_meses_deposito',
            field=models.IntegerField(default=2, help_text='Cantidad de meses exigidos como depósito por defecto'),
        ),
    ]
