# Generated by Django 5.2.10 on 2026-03-21 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0009_contrato_monto_adelanto_contrato_monto_deposito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('TRIAL', 'Plan de Prueba (14 días)'), ('BASIC', 'Plan Básico'), ('PREMIUM', 'Plan Premium')], default='TRIAL', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida (Falta de Pago)'), ('CANCELADA', 'Cancelada'), ('TRIAL', 'Trial (Prueba)')], default='TRIAL', max_length=20)),
                ('fecha_proximo_pago', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
