# Generated by Django 5.2.10 on 2026-03-21 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0010_suscripcioncliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('info', 'Informativo (Azul)'), ('warning', 'Advertencia (Amarillo)'), ('danger', 'Urgente (Rojo)'), ('success', 'Éxito (Verde)')], default='info', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, se mostrará en el header de todos los usuarios.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSaaS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('limite_propiedades', models.IntegerField(default=50, help_text='Límite de propiedades permitidas')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='suscripcioncliente',
            name='plan',
            field=models.CharField(default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='suscripcioncliente',
            name='plan_saas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='gestion_propiedades.plansaas'),
        ),
    ]
