# Generated by Django 5.2.10 on 2026-03-21 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0012_inquilino_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avisosistema',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de expiración del aviso', null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('INACTIVO', 'Archivado / Retirado')], default='DISPONIBLE', max_length=20),
        ),
        migrations.CreateModel(
            name='FacturaSaaS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propiedades_cobradas', models.IntegerField(default=0, help_text='Cantidad de propiedades facturadas a $1 c/u')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_saas/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_saas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
