# Generated by Django 6.0.2 on 2026-03-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0014_alter_accesoportafolio_id_alter_avisosistema_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si la propiedad fue eliminada lógicamente (Soft Delete)'),
        ),
    ]
