# Generated by Django 6.0.2 on 2026-03-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0015_propiedad_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientounidad',
            name='categoria',
            field=models.CharField(choices=[('REPARACION', 'Reparación'), ('PREVENTIVO', 'Mantenimiento Preventivo'), ('MEJORA', 'Mejora'), ('LIMPIEZA', 'Limpieza y Acondicionamiento'), ('OTRO', 'Otros Gastos / Misceláneos')], max_length=20),
        ),
    ]
