# Generated by Django 6.0.2 on 2026-03-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0016_alter_mantenimientounidad_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='recibir_alertas_correo',
            field=models.BooleanField(default=True, help_text='Apaga este interruptor si el inquilino prefiere no recibir correos automáticos de cobranza.'),
        ),
    ]
