# Generated by Django 6.0.2 on 2026-04-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0017_inquilino_recibir_alertas_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_dolar_manual', models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío, el sistema usará la tasa automática de internet. Si se coloca un valor, se forzará este valor.', max_digits=10, null=True)),
            ],
        ),
    ]
