# Generated by Django 6.0.2 on 2026-04-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0018_configuracionglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='direccion_fisica',
            field=models.TextField(blank=True, help_text='Dirección física del negocio', null=True),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='eslogan',
            field=models.CharField(blank=True, help_text='Eslogan del negocio', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=50, null=True),
        ),
    ]
