# Generated by Django 6.0.2 on 2026-04-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0019_portafolio_direccion_fisica_portafolio_eslogan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='logo_empresa',
            field=models.ImageField(blank=True, help_text='Logo oficial para imprimir en los recibos PDF', null=True, upload_to='portafolio_logos/'),
        ),
    ]
