# Generated by Django 6.0.2 on 2026-04-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0020_portafolio_logo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='formato_impresion',
            field=models.CharField(choices=[('A4', 'Hoja Estándar A4/Carta'), ('POS80', 'Ticketera Térmica 80mm'), ('POS58', 'Ticketera Térmica 58mm')], default='A4', help_text='Formato de recibos B2C', max_length=10),
        ),
    ]
