# Generated by Django 6.0.2 on 2026-04-20 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0021_portafolio_formato_impresion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopago',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que estaba logueado y registró este cobro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_cobrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
