# Generated by Django 6.0.2 on 2026-04-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0022_recibopago_registrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='foto_entrega_4',
            field=models.FileField(blank=True, null=True, upload_to='entregas_galeria/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='foto_entrega_5',
            field=models.FileField(blank=True, null=True, upload_to='entregas_galeria/'),
        ),
    ]
