# Generated by Django 6.0.2 on 2026-04-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0023_contrato_foto_entrega_4_contrato_foto_entrega_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasaas',
            name='usuarios_cobrados',
            field=models.IntegerField(default=0, help_text='Cantidad de usuarios extra facturados a $1 c/u'),
        ),
        migrations.AddField(
            model_name='suscripcioncliente',
            name='asistentes_gratuitos_extra',
            field=models.IntegerField(default=0, help_text='Otorga asientos VIP adicionales al plan base de 2.'),
        ),
    ]
