# Generated by Django 6.0.2 on 2026-04-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0024_facturasaas_usuarios_cobrados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='deuda_mora_migrada',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Moras no pagadas antes de Alquilo', max_digits=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='deuda_renta_migrada',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Renta acumulada no pagada antes de Alquilo', max_digits=10),
        ),
    ]
