# Generated by Django 6.0.2 on 2026-05-03 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0025_contrato_deuda_mora_migrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='texto_legal_generado',
            field=models.TextField(blank=True, help_text='Copia exacta del texto generado al momento de crear el contrato', null=True),
        ),
        migrations.CreateModel(
            name='PlantillaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Contrato Estándar, Contrato Comercial', max_length=150)),
                ('contenido', models.TextField(help_text='Contenido HTML del contrato con variables dinámicas')),
                ('es_predeterminada', models.BooleanField(default=False, help_text='Indica si es la plantilla del sistema')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('portafolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_contrato', to='gestion_propiedades.portafolio')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='plantilla',
            field=models.ForeignKey(blank=True, help_text='Plantilla base utilizada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_propiedades.plantillacontrato'),
        ),
    ]
