# Generated by Django 6.0.2 on 2026-05-20 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0026_contrato_texto_legal_generado_plantillacontrato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAumentoRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aumento', models.DateField(help_text='Fecha en que entra en vigencia el aumento')),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nuevo_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aumentos', to='gestion_propiedades.contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aumentos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_aumento', '-creado_en'],
            },
        ),
    ]
