# Generated by Django 6.0.2 on 2026-05-21 00:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0027_historialaumentorenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Hermoso Apartamento con Vista al Parque', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la propiedad, amenidades y condiciones.')),
                ('precio_renta', models.DecimalField(decimal_places=2, help_text='Precio de renta mensual en pesos ($)', max_digits=10)),
                ('telefono_contacto', models.CharField(help_text='Número de contacto para WhatsApp (Ej: +1809XXXXXXX)', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_activacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha en que se activó o renovó la publicación')),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_marketplace', to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicacion_marketplace', to='gestion_propiedades.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='marketplace_fotos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='gestion_propiedades.publicacionmarketplace')),
            ],
        ),
    ]
