# Generated by Django 5.2.10 on 2026-07-03 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0029_alter_accesoportafolio_id_alter_auditlog_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proceso', models.CharField(help_text='Ej: Generación de Rentas (Cron) o Generación de Rentas (Manual)', max_length=150)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('facturas_creadas', models.IntegerField(default=0)),
                ('detalles', models.TextField(blank=True, help_text='Mensaje de error, advertencia o resumen general', null=True)),
                ('ejecutado_por', models.ForeignKey(blank=True, help_text='Usuario que ejecutó, vacío si fue el cron', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
