# Generated by Django 5.2.10 on 2026-09-02 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0030_registroproceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropietarioInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo o razón social del propietario del inmueble', max_length=150)),
                ('cedula_o_rnc', models.CharField(blank=True, help_text='Cédula o RNC fiscal', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('tipo_comision', models.CharField(choices=[('PORCENTAJE', 'Porcentaje sobre Cobro (%)'), ('FIJO', 'Monto Fijo Mensual ($)')], default='PORCENTAJE', max_length=20)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: 10.00 para 10%', max_digits=5)),
                ('monto_comision_fijo', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto fijo si aplica tipo FIJO', max_digits=10)),
                ('banco_nombre', models.CharField(blank=True, help_text='Ej: Banco Popular, Banreservas', max_length=100, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, help_text='Ej: Corriente, Ahorros', max_length=50, null=True)),
                ('numero_cuenta', models.CharField(blank=True, help_text='Número de cuenta para liquidaciones', max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios_inmuebles', to='gestion_propiedades.portafolio')),
            ],
        ),
        migrations.CreateModel(
            name='GastoGeneralPropietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Descripción del gasto o deducción', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('GESTION_LEGAL', 'Gestión Legal / Abogado'), ('IMPUESTO_COMISION', 'Impuestos de Comisión / ITBIS / Retenciones'), ('HONORARIOS', 'Honorarios Profesionales'), ('REPARACION_GENERAL', 'Gastos Generales no asignados a propiedad'), ('PUBLICIDAD', 'Publicidad y Mercadeo'), ('OTRO', 'Otros Gastos / Deducciones')], default='OTRO', max_length=30)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('factura_adjunta', models.FileField(blank=True, null=True, upload_to='gastos_comprobantes/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_generales', to='gestion_propiedades.portafolio')),
                ('propiedad', models.ForeignKey(blank=True, help_text='Propiedad específica si aplica (Opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_directos_adicionales', to='gestion_propiedades.propiedad')),
                ('propietario_inmueble', models.ForeignKey(blank=True, help_text='Propietario al que aplica el gasto (Opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_generales', to='gestion_propiedades.propietarioinmueble')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario_inmueble',
            field=models.ForeignKey(blank=True, help_text='Dueño/Propietario del inmueble (Opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='gestion_propiedades.propietarioinmueble'),
        ),
        migrations.CreateModel(
            name='LiquidacionPropietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.IntegerField(help_text='Mes de liquidación (1-12)')),
                ('periodo_anio', models.IntegerField(help_text='Año de liquidación (Ej: 2026)')),
                ('monto_rentas_cobradas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_gastos_propiedades', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_gastos_generales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_neto_pagado', models.DecimalField(decimal_places=2, default=0.0, help_text='Neto transferido al propietario', max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Liquidado / Pagado')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, help_text='Ej: Transferencia Bancaria, Cheque, Efectivo', max_length=50, null=True)),
                ('referencia_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('propietario_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='gestion_propiedades.propietarioinmueble')),
            ],
            options={
                'ordering': ['-periodo_anio', '-periodo_mes'],
                'unique_together': {('propietario_inmueble', 'periodo_mes', 'periodo_anio')},
            },
        ),
    ]
