# Generated by Django 5.2.10 on 2026-09-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0031_propietarioinmueble_gastogeneralpropietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietarioinmueble',
            name='monto_comision_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Monto fijo si aplica tipo FIJO', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propietarioinmueble',
            name='porcentaje_comision',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Ej: 10.00 para 10%', max_digits=5, null=True),
        ),
    ]
