# Generated by Django 5.2.10 on 2026-09-02 01:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0032_alter_propietarioinmueble_monto_comision_fijo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionDepositoInquilino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_deposito_original', models.DecimalField(decimal_places=2, default=0.0, help_text='Fianza inicial entregada', max_digits=10)),
                ('monto_deduccion_facturas', models.DecimalField(decimal_places=2, default=0.0, help_text='Deducción por rentas o moras pendientes', max_digits=10)),
                ('monto_deduccion_danos', models.DecimalField(decimal_places=2, default=0.0, help_text='Deducción por reparaciones de daños', max_digits=10)),
                ('monto_neto_devuelto', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo neto devuelto (+) o a cobrar (-)', max_digits=10)),
                ('estado', models.CharField(choices=[('DEVUELTO', 'Saldo Devuelto al Inquilino'), ('RETENIDO_TOTAL', 'Depósito Retenido Totalmente por Deuda/Daños'), ('SALDO_PENDIENTE_INQUILINO', 'Inquilino Quedó Debiendo Saldo Adicional')], default='DEVUELTO', max_length=30)),
                ('fecha_liquidacion', models.DateField(default=datetime.date.today)),
                ('metodo_devolucion', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('NO_APLICA', 'No Aplica / Retención Total')], default='TRANSFERENCIA', max_length=30)),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de transferencia o cheque', max_length=100, null=True)),
                ('detalles_danos', models.TextField(blank=True, help_text='Explicación detallada de los daños o arreglos aplicados', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion_deposito', to='gestion_propiedades.contrato')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
