# Generated by Django 5.2.10 on 2026-09-02 15:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0033_liquidaciondepositoinquilino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Foto principal o fachada de la propiedad', null=True, upload_to='propiedades_fotos/'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS Latitud (Ej: 18.486058)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS Longitud (Ej: -69.931211)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio_alquiler_sugerido',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Precio de alquiler sugerido / publicado ($)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='HistorialPrecioPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nuevo_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(choices=[('AJUSTE_MERCADO', 'Ajuste de Precio de Lista / Mercado'), ('AUMENTO_CONTRATO', 'Aumento por Renovación o Contrato'), ('MEJORA_PROPIEDAD', 'Mejora o Remodelación de Unidad'), ('OTRO', 'Otro Motivo')], default='AJUSTE_MERCADO', max_length=30)),
                ('notas', models.TextField(blank=True, help_text='Justificación o detalles del cambio de precio', null=True)),
                ('fecha_cambio', models.DateField(default=datetime.date.today)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='gestion_propiedades.propiedad')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_cambio', '-creado_en'],
            },
        ),
    ]
