# Generated by Django 5.2.10 on 2026-09-03 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0034_propiedad_imagen_principal_propiedad_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='custodia_deposito',
            field=models.CharField(choices=[('ADMINISTRADORA_CUENTA', 'Retenido en Cuenta de Administradora'), ('BANCO_CERTIFICADO', 'En Banco (Certificado de Depósito)'), ('ENTREGADO_PROPIETARIO', 'Entregado al Propietario del Inmueble')], default='ADMINISTRADORA_CUENTA', help_text='Ubicación física del depósito de fianza', max_length=30),
        ),
        migrations.AddField(
            model_name='contrato',
            name='detalles_custodia_deposito',
            field=models.CharField(blank=True, help_text='Ej: Certificado #987654 Banco Popular o Entregado al propietario según recibo X', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='adjunto_cedula_fiador',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes_adjuntos/'),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='adjunto_cedula_solicitante',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes_adjuntos/'),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='adjunto_ingresos_fiador',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes_adjuntos/'),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='adjunto_ingresos_solicitante',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes_adjuntos/'),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='fiador_cedula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='fiador_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='fiador_direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='fiador_empresa_trabajo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='fiador_ingresos_mensuales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='fiador_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='fiador_puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='fiador_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='motivo_devolucion',
            field=models.TextField(blank=True, help_text='Nota explicativa enviada al prospecto al devolver el formulario', null=True),
        ),
        migrations.AddField(
            model_name='solicitudalquiler',
            name='tiene_fiador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitudalquiler',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador (Configurando preguntas)'), ('ENVIADA', 'Link enviado al prospecto'), ('RECIBIDA', 'Formulario Completado (Lista para evaluar)'), ('APROBADA', 'Aprobada (Lista para contrato)'), ('DEVUELTA_PARA_CORRECCION', 'Devuelta para Corrección / Cambiar Garante'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=30),
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades_galeria/')),
                ('titulo_o_descripcion', models.CharField(blank=True, help_text='Ej: Habitación Principal, Balcón, Cocina', max_length=150, null=True)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_galeria', to='gestion_propiedades.propiedad')),
            ],
        ),
    ]
