# Generated by Django 5.2.10 on 2026-09-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0035_contrato_custodia_deposito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='custodia_deposito',
            field=models.CharField(choices=[('ADMINISTRADORA_CUENTA', 'Retenido en Cuenta de Administradora'), ('BANCO_CONSIGNACION', 'En Banco (Consignación)'), ('ENTREGADO_PROPIETARIO', 'Entregado al Propietario del Inmueble')], default='ADMINISTRADORA_CUENTA', help_text='Ubicación física del depósito de fianza', max_length=30),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='detalles_custodia_deposito',
            field=models.CharField(blank=True, help_text='Ej: Consignación No. 987654 Banco Agrícola/Popular o Entregado al propietario según recibo X', max_length=255, null=True),
        ),
    ]
