# Generated by Django 5.2.10 on 2026-10-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedades', '0036_alter_contrato_custodia_deposito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='recordatorio_vencimiento_meses',
            field=models.IntegerField(choices=[(0, 'Sin recordatorio'), (1, '1 mes antes del vencimiento'), (2, '2 meses antes del vencimiento'), (3, '3 meses antes del vencimiento')], default=1, help_text='Anticipación con la que se mostrará la alerta de vencimiento en el Dashboard'),
        ),
    ]
